apiVersion: v1
kind: Pod
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  containers:
  - name: mysql
    image: 482485767515.dkr.ecr.us-east-1.amazonaws.com/mysql:v0.1
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "pw"
    ports:
    - containerPort: 3306
  imagePullSecrets:
  - name: regcred