apiVersion: v1
kind: Pod
metadata:
  name: web
  labels:
    app: employees
spec:
  containers:
  - name: web
    image: 482485767515.dkr.ecr.us-east-1.amazonaws.com/webapp:v0.1
    env:
    - name: DBHOST
      value: "10.244.0.8"
    - name: DBPORT
      value: "3306"
    - name: DBUSER
      value: "root"
    - name: DBPWD
      value: "pw"
    ports:
    - containerPort: 8080    
  imagePullSecrets:
    - name: regcred